project:
  type: website
  output-dir: docs

website:
  title: "BST 260: Introduction to Data Science"
  site-url: http://datasciencelabs.github.io/2024
  repo-url: https://github.com/datasciencelabs/2024
  repo-branch: main
  repo-actions: [source]
  sidebar:
    background: primary
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/datasciencelabs/2024
        text: GitHub
    style: docked
    contents:
    - href: index.qmd
      text: Home
    - href: syllabus.qmd
      text: Syllabus
    - href: schedule.qmd
      text: Schedule
    - href: psets.qmd
      text: Problem Sets
        
format:
  html:
    theme: 
     - journal
     - style.css
    toc: true
    repo-actions: [source, issue]


editor: source

