---
title: "Schedule"
---

All dates are subject to change.

## Lectures 

Part  |   Dates   | Slides | Reading |
|:-------------------|:---------|:----------|:----------|
Productivity Tools| Sep 04, Sep 09 | [Intro](slides/intro.qmd), [Unix](slides/productivity/unix.qmd) | Installing R and RStudio on [Windows](https://teacherscollege.screenstepslive.com/a/1108074-install-r-and-rstudio-for-windows) or [Mac](https://teacherscollege.screenstepslive.com/a/1135059-install-r-and-rstudio-for-mac), [Getting Started](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/getting-started.html), [Unix](http://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/unix.html), [RStudio Projects, Quarto](https://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/reproducible-projects.html), [Git and GitHub](http://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/git.html) |
R | Sep 11, Sep 16, Sep 19 | |[R Basics](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/R-basics.html), [Vectorization](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/programming-basics.html#sec-vectorization), [dplyr](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/tidyverse.html), [dates and times](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/dates-and-times.html), [ggplot2](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/ggplot2.html) |
| Wrangling | Sep 23, Sep 25 | |[Importing data](https://rafalab.dfci.harvard.edu/dsbook-part-1/R/importing-data.html), [Locales](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/locales.html), [Reshaping Data](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/reshaping-data.html), [Joining Tables](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/joining-tables.html), [Extracting data from the web](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/web-scraping.html)|
| Data visualization | Sep 30, Oct 02 | | [Distributions](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/distributions.html), [Dataviz Principles](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/dataviz-principles.html) |
|  Probability | Oct 07, Oct 09  | | [Monte Carlo](http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/continuous-probability.html#monte-carlo), [Random Variables & CLT](http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/random-variables-sampling-models-clt.html)|
| Inference | Oct 21, Oct 23  | | [Parameters & Estimates](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/parameters-estimates.html), [Confidence Intervals](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/confidence-intervals.html)|
|  Statistical Models | Oct 28, Oct 30  | | [Data-driven Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/models.html),  [Bayesian Statistics](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/bayes.html), [Hierarchical Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/hierarchical-models.html) |
|  Linear models | Nov 04, Nov 06, Nov 13  | |  [Regression](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/regression.html), [Multivariate Regression](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/multivariate-regression.html), [Measurement Error Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/measurement-error-models.html), [Treatment Effect Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/treatment-effect-models.html), [Association Tests](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-tests.html), [Association Not Causation](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-not-causation.html) |
| High dimensional data| Nov 18, Nov 20 | | [Matrices in R](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/matrices-in-R.html), [Applied Linear Algebra](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/linear-algebra.html), [Dimension Reduction](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/dimension-reduction.html) |
| Machine Learning | Dec 02, Dec 04, Dec 09, Dec 11 | |[Notation and terminology](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/notation-and-terminology.html), [Evaluation Metrics](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/evaluation-metrics.html), [conditional probabilities](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/conditionals.html), [smoothing](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/smoothing.html) ,[Resampling methods](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/resampling-methods.html), [ML algorithms](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/algorithms.html), [ML in practice](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/ml-in-practice.html) |
| Other topics | Dec 16, Dec 18 | |

## Problem sets

| Problem set| Topic | Due Date  set |  Difficulty |
|:-------|:--------------|:---------|:----------|
| [01](psets/pset-01-unix-quarto.qmd)   |  Unix, Quarto|Sep 10   | easy | 
| 02          |  R | Sep 13   |easy | 
| 03          |  Tidyverse | Sep 19   |easy | 
| 04          | Wrangling | Sep 26   | medium | 
| 05          |  Covid 19 data visualization | Oct 04   |medium | 
| 06          | Probability | Oct 11   | easy | 
| 07          | Predict the election |Nov 01   |  hard | 
| 08          | Confidence intervals for excess mortality |Nov 15   |  hard | 
| 09          | Matrices | Nov 22   | easy | 
| 10          | Digit reading | Dec 13   | hard | 
|Final Project| Your choice | Dec 20   | hard  |


