# Syllabus {.unnumbered}

## Course Information

- BST 260 Introduction to Data Science
- Kresge 202A and 202B (HSPH)
- Monday 09:45 AM - 11:15 AM; Wednesday 09:45 AM - 11:15 AM
- Lecture notes: [https://datasciencelabs.github.io/2024/](https://datasciencelabs.github.io/2024/)

## Prerequisites

We assume students have taken or are taking a probability and statistics course and have basic programming skills. 

Students not matriculated in an HSPH Biostatistics graduate program (HDS SM60, BIO SM80 / SM60 / SM1, and CBQG SM80) will be required to pass (score 18 out of 20 or higher) on a basic math and programming diagnostic test to enroll in the course. If you are in a HSPH Biostatistics graduate program and you score less than 18 we will contact you to offer supplementary resource to help you be prepared for the course.

## Textbooks

- [Introduction to Data Science: Data Wrangling and Visualization with R](http://rafalab.dfci.harvard.edu/dsbook-part-1/)
- [Introduction to Data Science:: Statistics and Prediction Algorithms Through Case Studies](http://rafalab.dfci.harvard.edu/dsbook-part-2/)

## Course Description

This course introduces the following:

* UNIX/Linux shell.
* Reproducible document preparation with RStudio, knitr, and markdown
* Version control with git and GitHub
* R programming
* Data wrangling with dplyr and data.table
* Data visualization with ggplot2

We also demonstrate how the following concepts are applied in data analysis:

* Monte Carlo simulations
* Statistical modeling
* High-dimensional data techniques
* Machine learning

We do not cover the theory and details of these methods as they are covered in other courses.

Throughout the course, **we use motivating case studies and data analysis problem sets based on challenges similar to those you encounter in scientific research**. 


## Weekly Course Structure

* Monday lectures: we describe the concerts, methods, and skills needed for problem sets.
* Wednesday labs: We work together on problem sets.
* Friday: problem sets due (see Key dates)

**Lectures will not be recorded.**

We will have a Slack workspace for you to ask questions during and after class.

## Grade Distribution

| Component | Weight |
|-----------|--------|
| 10 problem sets | 50% |
| Midterm 1 | 10% |
| Midterm 2 | 20% |
| Final project | 20% |

## Problem Sets 

Problem sets will be due every week or every other week, depending on difficulty.

Some problem sets include open ended questions that will be difficult to answer on your own. **We will be working on these together during Wednesday labs**. We also offer office hours where you can get help with unanswered questions.

Problem sets must be submitted via GiHub. **Students are required to have a GitHub account and create a repository for the course.**  We will be providing further instructions during the first lab.

10% of the total points for the problem sets will be deducted for every late day. **Students can have a total of 4 late days without penalty during the entire semester.** No need to provide a written excuse. **Providing an excuse does not give you more days** unless an accommodation is requested and approved by the Office of Student Affairs (this includes COVID).

Problem set submissions need to be completely reproducible Quarto documents.**If your Quarto file does not compile** it will be considered a late day, and you will be notified and will  need to resubmit a Quarto file that does compile. You will be deducted further late days for every day it takes for you to turn in a Quarto file that does knit. **You are required to check emails that come through the Canvas system**, as this the only way  we will communicate problems with your problem sets.


## Midterm Policy

**Both midterms are closed book, no internet, and in-class**. 
You are expected to complete them in 1 hour. 

Questions will be drawn mostly or entirely from the problem sets.

Please make sure you can come to class on the midterm dates provided in the **Key Dates** table below. If you miss the exam, you will need approval from the Office of Student Affairs to receive a makeup. All make-up exams will be completely different from the in-class ones.

## Final Project

For your final project we ask that you turn in a 4-6 page report using data to answer a public health related question. You can chose from one of the following:

* Based on state-level data, how effective where vaccines against SARS-CoV-2 reported cases and COVID-19 hospitalizations and deaths, and vaccination rates.
* What was the excess mortality after Hurricane María in Puerto Rico? Where different age groups affected differently?
 
Optionally, you can select a question that align with your ongoing research. This way, it can be directly beneficial to your work. This will require prior approval from the instructor by October 25.

Yet another option is to build a interactive webpage with poll-driven predictions for the 2024 US elections. Note this will be more challenging as we will not cover tools for interactive webpages until the last week of class (time permitting).

**Note: You should start working on your project after the first midterm. Do not wait until the last week**. Teaching staff will be available during office hours.

## ChatGPT Policy

You can use ChatGPT however you want. Do remember **you won't be able to use it during the midterms.**

## Key Dates - Subject to Change After First Week of Class

| Date | Event |
|------|-------|
| Oct 14  | No class: Indigenous Peoples Day |  
| Oct 16 | Midterm 1|
| Oct 23 | Start final project. Obtain approval if you want to do personal project instead.|
| Nov 11 | No class: Veterans' Day|           
| Nov 25 | Midterm 2|           
| Nov 27 | No class: Thanksgiving Recess Begins |          
| Dec 20 |  Final Project  due| 

## Preliminary Schedule

| Dates   | Topic  |  Links to readings and notes  |
|:-------------------|:---------|:----------|
| Sep 04 | Productivity Tools | Installing R and RStudio on [Windows](https://teacherscollege.screenstepslive.com/a/1108074-install-r-and-rstudio-for-windows) or [Mac](https://teacherscollege.screenstepslive.com/a/1135059-install-r-and-rstudio-for-mac), [Getting Started](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/getting-started.html) [Unix](http://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/unix.html) |
| Sep 09 | Productivity Tools | [RStudio Projects, Quarto](https://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/reproducible-projects.html) [Git and GitHub](http://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/git.html) |
| Sep 10 | **Problem Set 1 due**| Difficulty: easy| 
| Sep 11 | R | [R Basics](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/R-basics.html), [Vectorization](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/programming-basics.html#sec-vectorization) |
| Sep 13 | **Problem Set 2 due**| Difficulty: easy| 
| Sep 16, Sep 18 | R | [dplyr](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/tidyverse.html), [dates and times](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/dates-and-times.html), [ggplot2](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/ggplot2.html) |
| Sep 19 | **Problem Set 3 due**| Difficulty: easy| 
| Sep 23, Sep 25 | Wrangling | [Importing data](https://rafalab.dfci.harvard.edu/dsbook-part-1/R/importing-data.html) [Locales](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/locales.html) [Reshaping Data](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/reshaping-data.html), [Joining Tables](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/joining-tables.html), [Extracting data from the web](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/web-scraping.html)|
| Sep 26 |  **Problem Set 4 due**| Difficulty: medium| 
| Sep 30, Oct 02 | Data visualization |  [Distributions](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/distributions.html), [Dataviz Principles](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/dataviz-principles.html) |
| Oct 04 | **Problem Set 5 due**| Difficulty: medium| 
| Oct 07, Oct 09  |  Probability | [Monte Carlo](http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/continuous-probability.html#monte-carlo), [Random Variables & CLT](http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/random-variables-sampling-models-clt.html)|
| Oct 11 |  **Problem Set 6  due**| Difficulty: easy|  
| Oct 14  | No class | Indigenous Peoples Day |  
| Oct 16 | **Midterm 1**| Covers material from Sep 04-Oct 11|
| Oct 21, Oct 23 | Inference | [Parameters & Estimates](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/parameters-estimates.html), [Confidence Intervals](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/confidence-intervals.html)|
| Oct 28, Oct 30  |  Statistical Models | [Data-driven Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/models.html),  [Bayesian Statistics](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/bayes.html), [Hierarchical Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/hierarchical-models.html) | 
| Nov 01 | **Problem Set 7 due** | Difficulty: hard |
| Nov 04, Nov 06 |  Linear models |  [Regression](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/regression.html), [Multivariate Regression](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/multivariate-regression.html)|
| Nov 11 | No class| Veterans' Day|           
| Nov 13 | Linear models | [Measurement Error Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/measurement-error-models.html), [Treatment Effect Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/treatment-effect-models.html), [Association Tests](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-tests.html), [Association Not Causation](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-not-causation.html) |
| Nov 15 | **Problem Set 8  due** |Difficulty: hard| 
| Nov 18, Nov 20| High dimensional data | [Matrices in R](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/matrices-in-R.html), [Applied Linear Algebra](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/linear-algebra.html), [Dimension Reduction](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/dimension-reduction.html) |           
| Nov 22 | **Problem Set 9  due**| Difficulty: easy|  
| Nov 25 | **Midterm 2**| Covers material from Sep 04-Nov 22 |           
| Nov 27 | No class |Thanksgiving Recess Begins |          
| Dec 02, Dec 04 | Machine Learning | [Notation and terminology](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/notation-and-terminology.html), [Evaluation Metrics](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/evaluation-metrics.html), [conditional probabilities](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/conditionals.html), [smoothing](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/smoothing.html) | 
| Dec 09, Dec 11 | Machine Learning | [Resampling methods](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/resampling-methods.html), [ML algorithms](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/algorithms.html), [ML in practice](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/ml-in-practice.html) |           
| Dec 13 |  **Problem Set 10  due**| Difficulty: hard|  
| Dec 16, Dec 18 | Other topics | |           
| Dec 20 |  **Final Project  due**| |  




