# Problem set 1 {.unnumberd}

(@) Start an RStudio project. Recommended name: `pset-01-rmarkdown`

(@) Write a Quarto document that defines variables $a=1, b=-1, c=-2$
and print out the solutions to $f(x) = ax^2+bx+c=0$. 
Do not report complex solutions, only real numbers. Call the document `beginning.qmd`


(@) Include a graph of $f(x)$ versus $x$ for $x \in (-5,5)$.


```{r}
x <- seq(-5, 5, length = 100)
# hint: use the plot function
```

(@) Create a directory called `docs`. Use the command `quarto render` to create a PDF and save it the `docs` directory. Show use the command you typed:

```
# Your code here
```

(@) Use Unix to create a directory called `data` in the project home directory. Include the Unix command you used to create the directory.

```
# Your code here
```

(@) Use a terminal-based text editor to create a file `coefs.txt` in the `data` directory and save three coefficients, `1 -1 -2` for example. Show us the Unix commands you used to achieve this:

```
```

(@) Use Unix to copy the file `beginning.qmd` to file called `quadratic.qmd`. Show us the Unix command you used

```
```

(@) Edit the `quadratic.qmd` file to read in `a`, `b`, and `c` from the file `coefs.txt` instead of defining them. Make sure to use a relative path. As before, print out the solutions to $f(x) = ax^2+bx+c=0$. Do not report complex solutions, only real numbers. 


(@) Change the path of the file you are reading to `file.path(getwd(), "data/coefs.txt")`. Confirm that the files sill renders. Then move the entire `pset-01-rmarkdown` to a directory called `RtmpyDknq4`.  Does the file render? Change the path back to a relative path and see if it renders.



